In [37]:
import pandas as pd

df = pd.read_csv('Annual_Population_Estimates_for_New_York_State_and_Counties__Beginning_1970.csv')

In [38]:
df.head()

,FIPS Code,Geography,Year,Program Type,Population
0,36000,New York State,2021,Postcensal Population Estimate,19835913
1,36001,Albany County,2021,Postcensal Population Estimate,313743
2,36003,Allegany County,2021,Postcensal Population Estimate,46106
3,36005,Bronx County,2021,Postcensal Population Estimate,1424948
4,36007,Broome County,2021,Postcensal Population Estimate,197240

In [39]:
df.dtypes

FIPS Code        int64
Geography       object
Year             int64
Program Type    object
Population       int64
dtype: object

In [40]:
df['FIPS Code'] = df['FIPS Code'].astype(str)
df['Year'] = df['Year'].astype(str)

df.dtypes

FIPS Code       object
Geography       object
Year            object
Program Type    object
Population       int64
dtype: object

In [41]:
df.describe(include='all')

,FIPS Code,Geography,Year,Program Type,Population
count,3654,3654,3654,3654,3.654000e+03
unique,63,63,52,3,NaN
top,36000,New York State,1970,Intercensal Population Estimate,NaN
freq,58,58,126,2520,NaN
mean,NaN,NaN,NaN,NaN,5.922912e+05
std,NaN,NaN,NaN,NaN,2.351561e+06
min,NaN,NaN,NaN,NaN,4.438000e+03
25%,NaN,NaN,NaN,NaN,5.150125e+04
50%,NaN,NaN,NaN,NaN,8.831400e+04
75%,NaN,NaN,NaN,NaN,2.523632e+05
max,NaN,NaN,NaN,NaN,2.020125e+07

In [42]:
FIPS_dict = {'36061':'Manhattan', '36005':'Bronx', '36047':'Brooklyn', '36081':'Queens', '36085':'Staten Island'}
Year_list = ['2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021']

In [43]:
invalid_FIPS = list()

for i in df['FIPS Code']:
    if i not in FIPS_dict:
        invalid_FIPS.append(i)

In [44]:
df = df[df['FIPS Code'].isin(invalid_FIPS) == False]

In [45]:
invalid_year = list()

for i in df['Year']:
    if i not in Year_list:
        invalid_year.append(i)

In [46]:
df = df[df['Year'].isin(invalid_year) == False]

In [47]:
df.describe(include='all')

,FIPS Code,Geography,Year,Program Type,Population
count,60,60,60,60,6.000000e+01
unique,5,5,11,2,NaN
top,36005,Bronx County,2020,Postcensal Population Estimate,NaN
freq,12,12,10,55,NaN
mean,NaN,NaN,NaN,NaN,1.693395e+06
std,NaN,NaN,NaN,NaN,7.513344e+05
min,NaN,NaN,NaN,NaN,4.705970e+05
25%,NaN,NaN,NaN,NaN,1.420670e+06
50%,NaN,NaN,NaN,NaN,1.632332e+06
75%,NaN,NaN,NaN,NaN,2.312472e+06
max,NaN,NaN,NaN,NaN,2.736074e+06

In [50]:
df.drop_duplicates(subset=['FIPS Code', 'Geography', 'Year'], keep='last', inplace=True)

In [51]:
df.describe(include='all')

,FIPS Code,Geography,Year,Program Type,Population
count,55,55,55,55,5.500000e+01
unique,5,5,11,2,NaN
top,36005,Bronx County,2021,Postcensal Population Estimate,NaN
freq,11,11,5,50,NaN
mean,NaN,NaN,NaN,NaN,1.687831e+06
std,NaN,NaN,NaN,NaN,7.485176e+05
min,NaN,NaN,NaN,NaN,4.705970e+05
25%,NaN,NaN,NaN,NaN,1.419842e+06
50%,NaN,NaN,NaN,NaN,1.632326e+06
75%,NaN,NaN,NaN,NaN,2.305750e+06
max,NaN,NaN,NaN,NaN,2.736074e+06

In [52]:
import numpy as np

for county in FIPS_dict:
    df['Geography'] = np.where(df['FIPS Code'] == county, FIPS_dict[county], df['Geography'])

In [54]:
df.to_csv('popestimate_cleaned.csv', index=False)